name: linux

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        cxx: [ g++-10 ]
        build_type: [ Debug, Release ]
        std: [ 17 ]
        os: [ ubuntu-20.04 ]
        with_tests: [ ON ]

        include:
          # Build and test sanitizers
          - cxx: clang++-12
            build_type: Release
            os: ubuntu-20.04
            with_tests: ON
            cmake_options: -DLOCKFREE_QUEUES_SANITIZE_ADDRESS=ON

            # Build and test sanitizers
          - cxx: clang++-12
            build_type: Release
            std: 20
            os: ubuntu-20.04
            with_tests: ON
            cmake_options: -DLOCKFREE_QUEUES_SANITIZE_THREAD=ON

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: |
          sudo apt-get update
          ${{matrix.install}}
          cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        env:
          CXX: ${{matrix.cxx}}
          CXXFLAGS: ${{matrix.cxxflags}}
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{matrix.cmake_options}} \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} -DLOCKFREE_QUEUES_BUILD_TESTS=${{matrix.with_tests}} \
                -DLOCKFREE_QUEUES_BUILD_BENCHMARKS=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          threads=`nproc`
          cmake --build . --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: |
          threads=`nproc`
          ctest --build-config ${{matrix.build_type}} ${{matrix.ctest_options}} --output-on-failure
        env:
          CTEST_OUTPUT_ON_FAILURE: True