name: macos

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-11 ]
        build_type: [ Debug, Release ]
        std: [ 17 ]

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
                -DCMAKE_CXX_STANDARD=${{matrix.std}} -DLOCKFREE_QUEUES_BUILD_TESTS=ON \
                -DLOCKFREE_QUEUES_BUILD_BENCHMARKS=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --build-config ${{matrix.build_type}} --output-on-failure
