name: windows

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022 ]
        platform: [ x64 ]
        build_type: [ Debug, Release ]
        std: [ 17 ]
        with_tests: [ ON ]

    steps:
      - uses: actions/checkout@v3

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        shell: bash         # Use a bash shell for $GITHUB_WORKSPACE.
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ${{matrix.cmake_options}} \
                -A ${{matrix.platform}} -DCMAKE_CXX_STANDARD=${{matrix.std}} \
                -DLOCKFREE_QUEUES_BUILD_TESTS=${{matrix.with_tests}} \
                -DLOCKFREE_QUEUES_BUILD_BENCHMARKS=ON $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: |
          ctest --build-config ${{matrix.build_type}} --output-on-failure
